### ISSUE TITLE
Problema no TL 3020

### ISSUE THREAD

**Issue by condector** [simetnicbr/simetbox-openwrt-feed#1]
O sistema se instalou normalmente. Ele ativa a interface LAN (que mudei para DHCP) e ele é acessível na rede. Também funcionou o WIFI, tranquilo.

O problema é que na primeira tela (após a rede LAN ativar o DHCP e o SIMETBOX) que deveria aparecer no SIMET->Resultados do SIMET, está dando erro de:

![erro_simetbox](https://user-images.githubusercontent.com/2382325/26948235-9603376e-4c63-11e7-8353-49bc68c90d97.png)

O que eu poderia fazer?

**Comment by hmh** [comment]
Tente entrar na caixa com SSH, e remover o arquivo /etc/config/simetbox_hash_configured.  Feito isso, reinicie.

Existe uma PR aberta para o simetbox-openwrt-base que conserta um problema com a mudança do MAC da caixa por alteração nas configurações de rede. Pode ser que seja o causador do que você observou...

**Comment by hmh** [comment]
Como estamos retirando o suporte a caixas com menos que 8MiB de FLASH, infelizmente o TL3020 não mais será suportado em futuras versões do firmware "pronto" da SIMETBOX.  Note que não é só o SIMETBOX que estava sofrendo muito com restrição de tamanho de FLASH, o próprio LEDE/OpenWRT recomenda fortemente que não sejam utilizados equipamentos com menos de 8MiB de FLASH em 2017/2018.

A PR com as alterações para manejo automático do simetbox_hash_configured foram aceitas, e se realmente era essa a causa raiz desta issue, já está resolvida para quem faz o build do firmware simetbox a partir do github.  A outra causa raiz que conhecemos para a mensagem de erro acima é um problema transiente nos servidores do SIMET (a mensagem de erro deixa a desejar neste caso).

Por estes motivos, estou fechando esta issue.  Caso alguém descubra que a causa raiz do problema era outro, por favor reabra, ou crie uma nova issue report.
