### ISSUE TITLE
Archer C60(BR) Ver:3.0

### ISSUE THREAD

**Issue by danielmotaa** [simetnicbr/simetbox-openwrt-feed#22]
Bom dia amigos, tudo bem?
Estou com um Archer C60 só que na versão 3.0, posso rodar o 
simetbox-openwrt-18.06-snapshot-620-ar71xx-generic-archer-c60-**v2** nele?
Ele irá funcionar normalmente?

**Comment by hmh** [comment]
Daniel, vou pedir a compra de C60v3 aqui para nosso laboratório.

Não use a imagem v2 no seu C60v3 por enquanto, talvez até seja compatível, mas preciso verificar no openwrt.

**Comment by hmh** [comment]
Openwrt upstream: https://github.com/openwrt/openwrt/pull/2774

**Comment by hmh** [comment]
Daniel, não é a mesma imagem. Não utilize a imagem para v2.

**Comment by danielmotaa** [comment]
Certo, qual seria o próximo passo? Existe a possibilidade de atualização da imagem?

**Comment by hmh** [comment]
Quando o pessoal do OpenWRT terminar de adicionar o suporte, podemos gerar uma imagem teste e enviar para você, se você topar o risco de testar isso (e isso apenas se TFTP estiver funcionando. Sem TFTP é arriscado demais).

Caso contrário, vai ficar na dependência de recebermos duas unidades do C60v3 aqui no NIC.br para adicionar o suporte ao OpenWRT e SIMETBox.  Já fiz o pedido de compra, mas essas coisas podem ser imprevisíveis.

**Comment by hmh** [comment]
Suporte agora no OpenWRT master e 19.07, aguardando a chegada dos equipamentos no NIC.br para poder trabalhar nisso para a SIMETBox.

@danielmotaa, podemos criar imagens de teste por sua própria conta e risco, não existem instruções de como alterar o firmware do fabricante para ser aceito pelo TFTP recovery do fabricante (!), ou seja, não dá para reverter do SIMETBox/OpenWRT para o firmware original até que alguem descubra como.

**Comment by danielmotaa** [comment]
Boa tarde Henrique, a intenção é deixar esse equipamento apenas para uso do simetbox mesmo.
Se precisar esperar para atualizar não tem problema, gostaria de aplicar uma versão que eu saiba que não vá ter nenhum problema, sou um pouco leigo nessas configurações, é minha primeira vez utilizando o simet.
Fico no aguardo de um feedback para instalação. Esse roteador será utilizado em um parque tecnológico aqui no estado de São Paulo.

**Comment by hmh** [comment]
Ok.  Iremos então esperar até conseguirmos uma restauração de firmware via TFTP em laboratório antes de enviar qualquer imagem de firmware de teste.  Estamos no aguardo da finalização da compra e entrega de duas unidades do C60v3 no nosso laboratórios para prosseguir.

**Comment by danielmotaa** [comment]
Olá Henrique, bom dia!
Alguma novidade?

**Comment by hmh** [comment]
Os C60v3 chegaram, mas devido às atividades urgentes de apoio a alguns parceiros ref. covid19, vai demorar um pouco.

O C60v3 exige OpenWRT 19 e arquitetura "ath79".  Isso *não* está tão tranquilo quanto gostaríamos no openwrt, então serão imagens experimentais.

**Comment by hmh** [comment]
Utilizando OpenWRT 19.07 e arquitetura ath79, a quantidade de FLASH livre em todos os modelos da Archer C60 (v1, v2 e v3) simplesmente não é suficiente para as versões atuais do SIMETBox.

Estamos trabalhando em reduzir o footprint do OpenWRT necessário para a SIMETBox, mas o maior ofensor é o OpenSSL, e esse é um componente muito difícil de substituir.

Infelizmente, é necessário voltar atrás na previsão de suporte "em breve" para esse modelo.

**Comment by hmh** [comment]
Temos um firmware funcional, porém com as seguintes perdas *preliminares* de funcionalidade:

* Sem Zabbix
* Sem TR-069
* Sem transição IPv6 (464xlat, 6rd...) mas suporta IPv6 *nativo* sem prolemas.
* Sem alguns dos testes SIMET auxiliares

Vamos tentar melhorar isso, mas imagens oficiais não serão publicadas até termos certeza que atingimos um feature-set razoável, que será aplicado a todos os equipamentos com esse tipo de restrição de tamanho de memória FLASH livre.

A recomendação de compra de equipamentos passará a favorecer os equipamentos com 16MiB de FLASH como o Archer C6v2(US), em detrimento de equipamentos com 8MiB de FLASH (como o Archer C60v2/C60v3 (BR)).

Isso dito, imagens "experimentais" oficiais (que tem capacidade de autoatualização e de suporte) estarão disponíveis em breve via pedido por email no suporte@simet.nic.br.  É necessário informar o MAC do equipamento.

**Comment by hmh** [comment]
Imagens oficiais já estão disponíveis há alguns dias, versão 626.
https://simet.nic.br/simetbox/

Iremos suportar equipamentos com pouca FLASH livre como as TP-Link Archer C60 v1/v2/v3, dentre outros, através de uma variante da SIMETBox que foi apelidada "SIMETBox Lite", que *por padrão* tem as funcionalidades reduzidas descritas no último comentário.

Um "gerador de firmware" foi finalizado (mas ainda não é amigável o suficiente para expor/disponibilizar ao público), que permite trivialmente criar variações do SIMETBox Lite, por exemplo, com suporte a TR-069 ou Zabbix reinserido, contanto que tenha FLASH suficiente.  Essa funcionalidade está disponível para qualquer parceiro que entre em contato conosco (para ser parceiro, você precisa ter/estar instalando um parque de medidores um pouco numeroso. Não há custo).
