### ISSUE TITLE
Hash inválido. Verifique a URL utilizada

### ISSUE THREAD

**Issue by alansenairj** [simetnicbr/simetbox-openwrt-feed#8]
Modelo: tplink wr 1043nd

Não realiza mais testes automaticamente e não loga na página inicial

![image](https://user-images.githubusercontent.com/20565821/40699611-a92c1472-63ab-11e8-9ae7-93c90962b985.png)

**Comment by farribeiro** [comment]
Este seu problema é semelhante ao da issue simetnicbr/simetbox-openwrt-base#5 ?

**Comment by farribeiro** [comment]
Perdão, Referência errada... É a issue #1

**Comment by hmh** [comment]
Para qualquer assunto relacionado a "hash inválido":

1. Tente novamente após algumas horas. Este erro pode ocorrer por diversos motivos, um deles é um problema temporário nos servidores do SIMET.
1. Persistindo o problema por mais de 24 horas, contate a email de suporte do SIMETBOX e inclua o MAC address do equipamento, para que verifiquemos o problema no nosso lado.
